export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SET_ID = 'USER_SET_ID';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_COMPLETE = 'USER_REGISTER_COMPLETE';
export const USER_CONFIRMATION_SUCCESS = 'USER_CONFIRMATION_SUCCESS';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';
export const USER_PROFILE_RECEIVED = 'USER_PROFILE_RECEIVED';

export const QUIZ_LIST_REQUEST = 'QUIZ_LIST_REQUEST';
export const QUIZ_LIST_ERROR = 'QUIZ_LIST_ERROR';
export const QUIZ_LIST_RECEIVED = 'QUIZ_LIST_RECEIVED';
export const QUIZ_LIST_SET_PAGE = 'QUIZ_LIST_SET_PAGE';

export const QUIZ_REQUEST = 'QUIZ_REQUEST';
export const QUIZ_ERROR = 'QUIZ_ERROR';
export const QUIZ_RECEIVED = 'QUIZ_RECEIVED';
export const QUIZ_UNLOAD = 'QUIZ_UNLOAD';

export const QUIZ_PASSING_LIST_REQUEST = 'QUIZ_PASSING_LIST_REQUEST';
export const QUIZ_PASSING_LIST_RECEIVED = 'QUIZ_PASSING_LIST_RECEIVED';
export const QUIZ_PASSING_LIST_ERROR = 'QUIZ_PASSING_LIST_ERROR';
export const QUIZ_PASSING_LIST_UNLOAD = 'QUIZ_PASSING_LIST_UNLOAD';

export const QUIZ_PASSING_START_REQUEST = 'QUIZ_PASSING_START_REQUEST';
export const QUIZ_PASSING_START_ERROR = 'QUIZ_PASSING_START_ERROR';
export const QUIZ_PASSING_START_RECEIVED = 'QUIZ_PASSING_START_RECEIVED';
export const QUIZ_PASSING_START_UNLOAD = 'QUIZ_PASSING_START_UNLOAD';

export const QUIZ_PROCESS_REQUEST = 'QUIZ_PROCESS_REQUEST';
export const QUIZ_PROCESS_RECEIVED = 'QUIZ_PROCESS_RECEIVED';
export const QUIZ_PROCESS_ERROR = 'QUIZ_PROCESS_ERROR';
export const QUIZ_PROCESS_SET_CURRENT = 'QUIZ_PROCESS_SET_CURRENT';

export const QUIZ_PROCESS_QUESTION_REQUEST = 'QUIZ_PROCESS_QUESTION_REQUEST';
export const QUIZ_PROCESS_QUESTION_RECEIVED = 'QUIZ_PROCESS_QUESTION_RECEIVED';
export const QUIZ_PROCESS_QUESTION_ERROR = 'QUIZ_PROCESS_QUESTION_ERROR';
export const QUIZ_PROCESS_QUESTION_SET_SELECTED = 'QUIZ_PROCESS_QUESTION_SET_SELECTED';
export const QUIZ_PROCESS_QUESTION_SET_NEXT = 'QUIZ_PROCESS_QUESTION_SET_NEXT';

export const QUIZ_PROCESS_QUESTION_CHECK_ANSWER = 'QUIZ_PROCESS_QUESTION_CHECK_ANSWER';
export const QUIZ_PROCESS_QUESTION_CHECK_ANSWER_ERROR = 'QUIZ_PROCESS_QUESTION_CHECK_ANSWER_ERROR';
export const QUIZ_PROCESS_QUESTION_CHECK_ANSWER_RECEIVED = 'QUIZ_PROCESS_QUESTION_CHECK_ANSWER_RECEIVED';
export const QUIZ_PROCESS_QUESTION_CHECK_ANSWER_AGAIN = 'QUIZ_PROCESS_QUESTION_CHECK_ANSWER_AGAIN';
