export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SET_ID = 'USER_SET_ID';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_COMPLETE = 'USER_REGISTER_COMPLETE';
export const USER_CONFIRMATION_SUCCESS = 'USER_CONFIRMATION_SUCCESS';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';
export const USER_PROFILE_RECEIVED = 'USER_PROFILE_RECEIVED';

export const QUIZ_LIST_REQUEST = 'QUIZ_LIST_REQUEST';
export const QUIZ_LIST_ERROR = 'QUIZ_LIST_ERROR';
export const QUIZ_LIST_RECEIVED = 'QUIZ_LIST_RECEIVED';
export const QUIZ_LIST_SET_PAGE = 'QUIZ_LIST_SET_PAGE';

export const QUIZ_REQUEST = 'QUIZ_REQUEST';
export const QUIZ_ERROR = 'QUIZ_ERROR';
export const QUIZ_RECEIVED = 'QUIZ_RECEIVED';
export const QUIZ_UNLOAD = 'QUIZ_UNLOAD';

export const QUIZ_PASSING_LIST_REQUEST = 'QUIZ_PASSING_LIST_REQUEST';
export const QUIZ_PASSING_LIST_RECEIVED = 'QUIZ_PASSING_LIST_RECEIVED';
export const QUIZ_PASSING_LIST_ERROR = 'QUIZ_PASSING_LIST_ERROR';
export const QUIZ_PASSING_LIST_UNLOAD = 'QUIZ_PASSING_LIST_UNLOAD';

